In [1]:
import numpy as np

** One dimensional arrays **

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,9.9)

array([9.9, 9.9, 9.9, 9.9, 9.9, 9.9, 9.9, 9.9, 9.9, 9.9])

In [7]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [8]:
a[2]

3

In [9]:
a[5] = 8
a[5]

8

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

** Two / dimensional arrays **

In [17]:
#  first is no of rows, 2nd is no of columns
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
n[0,1]

2

In [26]:
n[0]

array([1, 2, 3])

In [30]:
n[:,2]

array([3, 6, 9])

In [31]:
n[1] = [10,11,12]

In [32]:
n

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 7,  8,  9]])

In [33]:
n[:,1] = [7,8,9]

In [34]:
n

array([[ 1,  7,  3],
       [10,  8, 12],
       [ 7,  9,  9]])

** Randomly generated arrays **

In [41]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [43]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [54]:
# np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[70, 86],
       [70, 19],
       [56, 82],
       [ 1, 68],
       [40, 81]])

** Element wise operations **

In [55]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a = a + 1 

In [57]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [59]:
a * a 

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

** Comparision operations **

In [60]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
b = a * a
b

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [62]:
a >= 2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [64]:
b > a

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [65]:
b[b>a]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100])

In [66]:
a.min()

1

In [67]:
a.max()

10

In [68]:
a.sum()

55

In [70]:
a.mean()

5.5

In [72]:
a.std()

2.8722813232690143